version: '3'

services:
  backend:
    build:
      context: ./end
    ports:
      - "3001:3001"
    depends_on:
      - database

  frontend:
    build:
      context: ./frontend
    ports:
      - "3000:3000"

  database:
    build:
      context: ./mongodb
